//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HARTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string Content { get; set; }
        public string Image { get; set; }
        public System.DateTime DateCreate { get; set; }
        public string Tag { get; set; }
        public int EmpId { get; set; }
        public int SubCategoryId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
