//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HARTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<byte> StarRate { get; set; }
        public int CustomerId { get; set; }
        public int TourId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
